# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 6 * * 0"
  workflow_dispatch:

name: update-data

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::pkgload
            any::rmarkdown
            any::ggplot2
            any::dplyr
            any::writexl
            local::.
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Update data
        run: |
          Rscript "data-raw/update.R"
      - name: Update README
        run: rmarkdown::render("README.Rmd", "github_document")
        shell: Rscript {0}
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m 'Update data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
